name: Proj_feedback

on:
  push:
    branches:
      - main

jobs:
  Project-feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
         python-version: 3.11

      - name: Install dependencies
        run: |
          cd main/project
          pip install -r requirements.txt  # Install project dependencies

# Run exercise feedback
      - name: Exercise feedback
        run: |
         chmod u+r+x ./main/project/tests.sh
         cd ./main/project
         ./tests.sh
